name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'type:new feature'
  - title: '🔬 Improvements'
    label: 'type:enhancement'
  - title: '🐞 Bug Fixes'
    label: 'type:bug'
  - title: '📦 Dependency updates'
    label: 'type:dependency'
  - title: '📄 Documentation updates'
    label: 'type:documentation'

change-template: '* $TITLE (via #$NUMBER) - @$AUTHOR'
template: |
  $CHANGES
  ## 👀 Links
  [Commits since $PREVIOUS_TAG](https://github.com/allure-framework/allure-ruby/compare/$PREVIOUS_TAG...master)
