require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - node_modules/**/*
    - '*/tmp/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '*/spec/**/*'

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: true
  Max: 15

Metrics/ModuleLength:
  Enabled: true
  Max: 150

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
  SafeAutoCorrect: true
