---
include:
  - "**/*.rb"
  - "**/*.rake"
  - Rakefile
exclude:
  - spec/**/*
  - vendor/bundle/**/*
require: []
domains: []
reporters:
  - rubocop
  - require_not_found
plugins:
  - runtime
require_paths: []
max_files: 5000
