# frozen_string_literal: true

require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(:test, :tag) do |t, args|
  args[:tag].tap do |tag|
    t.rspec_opts = "--color --require spec_helper --format documentation #{tag ? "--tag #{tag}" : ''}"
  end
end

RuboCop::RakeTask.new(:rubocop) do |task|
  task.options = %w[--parallel]
end
