# frozen_string_literal: true

require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(:test) do |t|
  t.rspec_opts = "--color --require spec_helper"
end

RuboCop::RakeTask.new(:rubocop) do |task|
  task.options = %w[--parallel]
end
