name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Test + Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x

      - name: Install
        run: |
          gem install bundler -v 2.0.2
          bundle install

      - name: Lint
        run: bundle exec rake rubocop

      - name: Test
        run: bundle exec rake test
