name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true

      - name: Validate release tag
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          version=$(cat ALLURE_VERSION)
          test "$RELEASE_TAG" = "${version}"

      - uses: rubygems/release-gem@v1
        with:
          await-release: false # release rake task includes release await
